---


- name: Sending the Log file
  hosts: localhost
  connection: local
  gather_facts: true

  vars_files:
    - ./email_vars.yml

  tasks:
    - block:
      - name: Sending Log File Report over mail
        include_role: 
         name: sendmail 
