    - name: Verify log file exists
      stat:
        path: "/home/ubuntu/Amit/aro-capacity-check/reports/"
      register: logfile

    - name: find all txt log files
      find:
        paths: "/home/ubuntu/Amit/aro-capacity-check/reports/"
        patterns: 
          - "*.csv"
          - "*.html"
          - "*.txt"
      register: all_log_files

    - name: Show found files
      debug:
        msg: "{{ all_log_files.files | map(attribute='path') | list }}" 

    - name: Send email with log attachment
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        from: "{{ sender }}"
        to: "{{ recipients }}"
        subject: "Health Check Report - DEV"
        subtype: html
        #body: "{{email_body}}" 
        body: "Please find the attached Health-check report.<br> Please do not <i>preview</i> but <b>open the html report on the browser</b> for best view.<br><br>" 

        attach: "{{ all_log_files.files | map(attribute='path') | list }}"
      when: all_log_files.files | length > 0  


